### ISSUE TITLE
Feature: Fireworks

### ISSUE THREAD

**Issue by godleydemon** [Codisimus/PhatLoots#10]
The ability to turn on fireworks when chest is opened: Height and Color at least. We setup a casino on our server and we thought it would be neat to have some type of effect to play when a chest was opened. Just an interesting thought bubble and possible feature to add.

**Comment by Codisimus** [comment]
I have declined this request as it could likely be done with an external plugin to create firework effects at a specific location. And a CommandLoot to trigger it.
