### ISSUE TITLE
Error with MythicDrops integration 

### ISSUE THREAD

**Issue by digitronic-games** [Codisimus/PhatLoots#21]
I'm getting this error in my console when starting up the server: http://pastebin.com/cuVfr0YJ, I'm using this version of MythicDrops https://www.spigotmc.org/resources/mythicdrops.6114/

**Comment by craigbett** [comment]
From what I understand this is a simple fix, looks like MythicDrops changed their name-spacing from  net.nunnerycode.bukkit.mythicdrops to com.tealcube.minecraft.bukkit.mythicdrops.

**Comment by ImZeus** [comment]
I've put in a Pull Request to fix everything that Nun broke on PhatLoots side when he changed package structure. We are just waiting on Codisimus to approve it.
