### ISSUE TITLE
OnEnable with 1.9

### ISSUE THREAD

**Issue by Drehverschluss** [Codisimus/PhatLoots#26]
Hello there.

I just found your new website and thought ill give the latest build a try for 1.9 but unfortunately i got a error on loading. 
http://pastebin.com/GqMrCbKF

Im also using MythinDrops combined with your plugin. Maby theres is the issue. I hope not. If you are planing to still support MythicDrops than you maby need to update something idk.
https://github.com/Nunnery/MythicDrops

Would be a shame if i need to drop your plugin cause i didnt find any better way so setup loottable so easy as your plugin provides it.

MFG

**Comment by Codisimus** [comment]
Yes, I still support the latest version of MythicDrops. I will look into this during my lunch.

**Comment by Drehverschluss** [comment]
Awesome your the greatest. Thx a lot.

I dont know if you can remember. But i have now a discustion with the MythicDrops author about  the UnidentifiedItem tier. He will now implement such a feature. (https://github.com/Nunnery/MythicDrops/issues/261)
 Maby you can get that to work later too. MFG
