### ISSUE TITLE
About MythicDrops

### ISSUE THREAD

**Issue by Drehverschluss** [Codisimus/PhatLoots#27]
Now since Myrhic Drops allready give us a option to define a unidentified items tier by the last line of the lore, and you are also already let us choose a Tier in the GUI, can you maby make it to that when i define a tier for the UnidItem that your plugin add a (hidden)Line to to last last line of the UnidentifiedItem lore?

MFG

**Comment by Codisimus** [comment]
I can set the last line of lore to the tier but there is no way for me to hide the text.

**Comment by Drehverschluss** [comment]
Ok just putting the last line of the lore would be great anyways. Maby the color code can be used to show different letters... But I don't know if the lore gets read correctly after.

**Comment by Nunnery** [comment]
The closest you can get to hiding the text is by making the color code black, but that's still visible. Unless I'm mistaken, Bukkit/Spigot still doesn't fully support manipulating NBT information. It probably doesn't persist over server restart either.

If it did persist, then we could talk about setting the tier by NBT tag and then using that information in MythicDrops.

**Comment by Drehverschluss** [comment]
Hmm what I remember messing with NBT data is not a good idea.  Could break a bit more if I remember correctly. 

I'll try out later a bit when I'm home than I give you a feedback.

**Comment by Codisimus** [comment]
I set the color to black for loot bags in this plugin. But after some research, it looks like you may be able to encode a string as colors by putting the color code character in front of each letter in the word. I have not tried it so I don't know if it works for letter which don't represent a color but others have claimed to use it.

As for storing it another way, back when Spigot added support to persist attributes, they also added another gem that looked like you could persist other data of your choosing. It proly hasn't made it to the API yet but I will add a link to that code change to see if it is something we would want to use.

**Comment by Codisimus** [comment]
Just found the ticket in my past emails https://hub.spigotmc.org/jira/browse/SPIGOT-581.

**Comment by Drehverschluss** [comment]
So that means you can easly now edit this without breaking that much.

But well i think there are easyer ways around this.

Anyways you maby have a build where the line get generated? So i can test a bit?

**Comment by Codisimus** [comment]
You can find [dev-build-48](https://github.com/Codisimus/PhatLoots/releases/tag/dev-build-48) under releases which adds the tier to the lore.

**Comment by Drehverschluss** [comment]
will test asap.

**Comment by Drehverschluss** [comment]
Nope thats not working :)
Well you are changing the whole lore. Instead you should check the existing lore and add it later

But yea it working you are adding the right text :P

Also what if you are using "&k" infront of the text? Isnt the text only visability different but MythicDrops should still read the line correctly right?

MFG

**Comment by Codisimus** [comment]
My bad, I was thinking it was a new item so it would never have lore. I will change it to look for existing lore/ItemMeta first.

As for using k, I can do that and MythicDrops should still read it fine. I just think the scrolling text is annoying. But if that is what you want, I will add it. Or maybe make it an option in the config.

**Comment by Drehverschluss** [comment]
Make a option in the Config is the best way i think :)

**Comment by Drehverschluss** [comment]
Is it still the Dev-build-48 ? If yes than its not working :( i still get only your text in black

**Comment by Codisimus** [comment]
My latest commit has a weird compile time error (https://travis-ci.org/Codisimus/PhatLoots#L233).
I will have to look into it more later today but it seems like they changed the API and I still have the old Javadocs.

**Comment by Drehverschluss** [comment]
ahh allright than ill whait for it :)

**Comment by Codisimus** [comment]
I tried to get the changes out before I left for the day but I didn't expect compiling problems.

I did however fix the issues you have mentioned.

**Comment by Drehverschluss** [comment]
awesome. your great :)

**Comment by Codisimus** [comment]
Ok, that should do it. As long as it works, I will add the config setting and call this closed. Unless @Nunnery wants to try to use one of the other options I mentioned earlier.

**Comment by Drehverschluss** [comment]
Works perfectly. 

I cant see any issue. Well option to choose how the text will be showed would be cool. But anyways it working great... Thx a lot for the great support

**Comment by Nunnery** [comment]
This works perfectly fine for me.

**Comment by Codisimus** [comment]
As long as changing the config options works correctly then I will close this ticket. Let me know if either of you get a chance to properly test it before I do.

**Comment by Codisimus** [comment]
@Drehverschluss were you able to try the config option? Does this meet all of your needs? If so I will close this issue.

**Comment by Drehverschluss** [comment]
Yes of course i can test it. Do i just need to redownload from https://github.com/Codisimus/PhatLoots/releases/tag/4.2.2 ??

**Comment by Codisimus** [comment]
Oh sorry, you can find the releases at https://github.com/Codisimus/PhatLoots/releases. Try the most recent dev build which will be at the top of the list.

**Comment by Drehverschluss** [comment]
Whyt config i need to look for?

**Comment by Drehverschluss** [comment]
- ==: UnidentifiedItem
        Durability: 0
        Probability: 50.0
        Tier: t0weapon <- Here?

**Comment by Codisimus** [comment]
You can find the option in the config.yml file. https://github.com/Codisimus/PhatLoots/blob/master/src/config.yml#L160

**Comment by Drehverschluss** [comment]
Oh ok this lines didnt get generated....needed to delete the config. But yea i think thats all i need ;)

**Comment by Drehverschluss** [comment]
Works as ecpected. Even you scare about the &k are unessecary. Because when you make it '&0&k' you cant even see it. :+1:

**Comment by Codisimus** [comment]
Great, if you need anything else regarding this or another feature, feel free to create a new ticket.
