### ISSUE TITLE
"/loot give all" command

### ISSUE THREAD

**Issue by Codisimus** [Codisimus/PhatLoots#31]
Add a command to give a PhatLoot to all online players

**Comment by tara81** [comment]
Can it also be per world / world support? 

I have a minigame world that players shouldnt get loot from . =)

**Comment by Codisimus** [comment]
Yes, that should be pretty easy to add in as well.

**Comment by tara81** [comment]
Much <3

**Comment by tara81** [comment]
I was tryin hard but it seems like using @a for all players in the world only works with a command block hahaha /loot give @a loot

**Comment by Codisimus** [comment]
I was going to make the command "/loot give all". Should I make it "/loot give @a" to match other Minecraft commands?

**Comment by tara81** [comment]
Oh i dont mind u can call it elephants for all i care ;D

**Comment by Codisimus** [comment]
This functionality is now available in [dev-build-62](https://github.com/Codisimus/PhatLoots/releases/tag/dev-build-62) with the command **/loot give all**

**Comment by tara81** [comment]
How exactly does this work ? I tried /loot give all phatloot and it just says wrong command

**Comment by tara81** [comment]
its telling me /loot give <player> phatloot , does that when a player doesnt exist ;P

**Comment by Codisimus** [comment]
I just downloaded dev-build-62 and it worked perfectly. Maybe try re-downloading it. Also, the syntax for the per world command can be seen by typing '/loot give help'
