### ISSUE TITLE
Break and Respawn doesn't work on manually added valid blocks.

### ISSUE THREAD

**Issue by Sparclen** [Codisimus/PhatLoots#32]
Break and respawn only works on chests and dispensers.
When you're using a different block as a phatloot container, all options work fine except for the break and respawn. It will just remain there after looting, like a non-breakandrespawn chest.

**Comment by Codisimus** [comment]
This has been added and is present in [dev-build-61](https://github.com/Codisimus/PhatLoots/releases/tag/dev-build-61)
