### ISSUE TITLE
PhatLoots v4.2.2 MythicDrops dependency issue.

### ISSUE THREAD

**Issue by Deathinflames** [Codisimus/PhatLoots#33]
Hello Codisimus!

We seem to be having a dependency issue with PhatLoots v4.2.2 dev-build-51 and MythicDrops according to this error: http://pastebin.com/gTEnuLYh

We have rolled back to the 4.2.2 version released on March 17, 2016, but we just thought we would let you know. :+1:

**Comment by Codisimus** [comment]
I have not seen this and I don't use MythicDrops myself. Did you use it sometime in the past? My guess is that you still have aN Unidentified Item in one of your loot tables

**Comment by Codisimus** [comment]
Disregard that, if rolling back fixed it then it must be something else. I will look at the exact changes that went in since that release.

**Comment by Codisimus** [comment]
I think maybe the new config option is causing it to look for those classes. Funny that I haven't had this happen to me yet though. I will fix it later today, thanks for finding this before I made it an official release.

**Comment by Codisimus** [comment]
This has been fixed in v4.2.3
