### ISSUE TITLE
Request Feature - Network booster- Better drops -  permission

### ISSUE THREAD

**Issue by tara81** [Codisimus/PhatLoots#36]
Enable a permission that allows players with the permission to have an increased chance to get loot drops . Example: A phatloot has a collection that has 2 items : A bow and a sword. The bow is at 20% chance and the sword is at 100% chance.  With the permission given, it raises the chances on all loot by 5% or 10% or 20% or 50% ! Depending on what you put in the configuration.

Could be a donator perk that is EULA compatible.

Config example:

Custom Permission1:
  Loot chance boost permission: phatloots.boost.10
  Loot chance boost percentage: 10
Custom Permission2:
  Loot chance boost permission: phatloots.boost.20
  Loot chance boost percentage: 20

**Comment by Mapleclaw** [comment]
oh hey tara lmao its MapleSucc

**Comment by Codisimus** [comment]
PhatLoots can easily support this as it already does something similar with mob loot. I was thinking about tying the Luck attribute to increased loots. But this would be much simpler. However, permission nodes defined in a config file goes against the Bukkit API so I may try to think of another way to do that.

**Comment by tara81** [comment]
well instead of making it in the config just make it so phatloots.boost.# where # is the percent amount increase

**Comment by tara81** [comment]
Just so we can configure how much of a boost we want to give

**Comment by tara81** [comment]
It doesn't have to be in the configuration, Just as long as we can select the amount increased :D

**Comment by Codisimus** [comment]
I just re-read the Bukkit documentation and I guess it doesn't actually say that you should dynamically create permissions like this. So that is what I will likely do.

**Comment by Codisimus** [comment]
Almost done with this... might have it for you tonight.

**Comment by tara81** [comment]
awesome to hear !

**Comment by tara81** [comment]
On the third night of xmas, my codi gave to me, 
3 new permissions,
2 new world loot commands,
and an addon that prevents ninja looting.

**Comment by Codisimus** [comment]
Just finished testing. there should be a dev build available later today. Hopefully during the noon hour if I have time during my lunch to commit the changes.

In the meantime, permission nodes for this are in the following format: _phatloots.bonus.#_ with decimal places are also supported i.e. _phatloots.bonus.10.5_. If a Player has multiple permission nodes then the bonuses get stacked. Remember that this is percentage based so anything over 100 is equivalent to 100%.

You will be required to register each number within the config file in an array format. i.e. _[0.5, 3, 10, 15.2, 25]_

**Comment by tara81** [comment]
awesome so the new config will have something like 
Bonus Perms: [0.5, 3, 10, 15.2, 25] ?

**Comment by Codisimus** [comment]
Yup!
https://github.com/Codisimus/PhatLoots/blob/master/src/config.yml#L117

**Comment by Codisimus** [comment]
And here is the dev build which includes this feature: https://github.com/Codisimus/PhatLoots/releases/tag/dev-build-77

**Comment by tara81** [comment]
does this work on 1.9.4 ? Whats your paypal again?

**Comment by Codisimus** [comment]
Yes, this supports versions 1.9 and above. My PayPal email is codisimus@gmail.com
