### ISSUE TITLE
Mobs dropping money, Nothing else.

### ISSUE THREAD

**Issue by sheeeeeeets** [Codisimus/PhatLoots#37]
Hey man.

First off, GREAT plugin.  I used this plugin on my old server for friends, and it was a HUGE hit to make mobs give money based on kill, to buy stuff in the shops.

When I first installed the plugin, I noticed that after making a loot table (same name as mob) and making the loot table drop money, that the mob killed ONLY dropped money.  To combat this is 1.8, I just looked up the exp that mobs dropped by default, and added that as well.

On my new 1.9.2 server, users are wanting to actually get the normal mob drops as well.  Right now, they only get exp and money, and mobs do not drop their loot other than what is specified.

IS there a way to ONLY add money per kill, per mob type, without having to go through EVERY loot table and add what a mob should drop?

**Comment by tara81** [comment]
Well my mobs are dropping loot along with the money i gave them ..

##Using MobLoot may cause significant lag if there are numerous mobs on the server
##e.g. Zombie, Creeper, Skeleton, Spider, Player
MobDropLoot: true
##e.g. ZombieSpawn, SkeletonSpawn, VillagerSpawn
MobSpawnLoot: true

**Comment by sheeeeeeets** [comment]
Yeah, I figured out quite a bit yesterday but forgot to update/close this.  This is an amazing plugin....  Thanks all!
