### ISSUE TITLE
Error when opening a loot chest [Spigot 1.8.8]

### ISSUE THREAD

**Issue by bittiez** [Codisimus/PhatLoots#38]
I could not find anywhere on your site that says what version of Spigot your plugin is supposed to support so that could very well be the problem, that being said this happens any time I try to open a chest:

http://pastebin.com/TVwzFRs1

**Comment by Codisimus** [comment]
Sorry @bittiez, It isn't very clear but I am working on adding the version numbers to the GitHub releases as seen on [release v4.2.3](https://github.com/Codisimus/PhatLoots/releases/tag/v4.2.3). The version you want is [v4.1.1](https://github.com/Codisimus/PhatLoots/releases/tag/v4.1.1) which still supports Minecraft 1.8.

**Comment by bittiez** [comment]
Thank you for informing me! Appreciate it!
