### ISSUE TITLE
/loot give all command

### ISSUE THREAD

**Issue by tara81** [Codisimus/PhatLoots#39]
How exactly does this work ? I tried **/loot give all [phatloot]** and it just says wrong command.

Also what is the command to do it per world?

Also can you try fixing up that plugin you made for no drop stealing :P

**Comment by Codisimus** [comment]
I just downloaded [dev-build-62](https://github.com/Codisimus/PhatLoots/releases/tag/dev-build-62) and it worked perfectly. Maybe try re-downloading it. Also, the syntax for the per world command can be seen by typing '/loot give help'
