### ISSUE TITLE
Request feature - command delay 

### ISSUE THREAD

**Issue by tara81** [Codisimus/PhatLoots#41]
Asking if you can add an ability to add a delayed command in phatloots.

example:
/loot add cmd delay 60 world /region flag reward entry deny world
/loot add cmd [delay] [amount] [world to execute/if Empty all worlds] [command]

What it does : after opening the phatloot, waits 60 seconds then runs the command in the world specified.

**Comment by Codisimus** [comment]
I completely missed this one... Should be easy to add.

**Comment by tara81** [comment]
is its usage the same as I asked or ?
