### ISSUE TITLE
Lootbags not working

### ISSUE THREAD

**Issue by Porama6400** [Codisimus/PhatLoots#44]
Lootbags not working
after i linked it , it says i has been link but nothing happened after click

**Comment by Porama6400** [comment]
PhatLoots ver. 4.1.1
Spigot 1.8.8

**Comment by tara81** [comment]
Use v 4.1.x if you are on spigot 1.8.8 

When you link a lootbag, it doesnt tell you it has been linked, which makes me think you have lootbags confused with phatloots.

**Phatloot: **A loot that can be linked to a chest/dispenser/etc according to config.
**Lootbag:** A phatloot that is linked to an item/block (like an enderchest item), useable by right clicking.

To create a Lootbag , You need a lore plugin like lores(made by the same guy) to add underlore.

Link to lores: http://dev.bukkit.org/bukkit-plugins/lores/ 

Then you need to add the name of the phatloot in the underlore which respects the key in the config. . 
Config Example:
##Using LootBags may cause lag if you have many items with a lot of lore on the server
LootBags: true
LootBagKey: '&3&0&k'

Finally, you hold the lootbag you want in your hand, and add the lore to the lootbag.
/lore add &a- Right click to Open!
/lore add &3&0&k<phatlootname>
