### ISSUE TITLE
Max Loot Amount

### ISSUE THREAD

**Issue by EthanRPro** [Codisimus/PhatLoots#52]
I'd like to limit my chests/lootbags to only ever giving out 1 item from the loot table per loot. Is this possible? currently my loots appear to randomly pick how many items a player will recieve

**Comment by Sketaful** [comment]
You need to put the things in a collection. It only picks one thing from each collection so if you just make one collection and put all loot inside that collection it will only pick one thing each time.

**Comment by Codisimus** [comment]
It looks like @Sketaful answered this. If you need additional information, you can go to my Youtube channel where I have a few tutorial videos for PhatLoots. The one you will likely find most useful is Create [Minecraft Loot using the PhatLoots Info GUI](https://www.youtube.com/watch?v=4SozpBRjK3g).
