### ISSUE TITLE
Loot GUI not working

### ISSUE THREAD

**Issue by leokiller97** [Codisimus/PhatLoots#53]
I'm getting this error while trying to do /loot info/gui:
http://pastebin.com/gMB0xPpm

Everything worked fine before, but then I restarted the server like every other time and PhatLoots' info command stopped working. I also had to reload all worlds from multiverse, not sure what happened after that restart. All chests and containers work perfectly, it's just the GUI.

EDIT: Spigot 1.9.4

**Comment by tara81** [comment]
what version of spigot and phatloots are you using ? It's working fine for me on 1.9.4

**Comment by leokiller97** [comment]
It works for me as well, sadly only on certain phatloots. Some of them don't work.
Spigot 1.9.4, last PhatLoots version.

**Comment by tara81** [comment]
are you sure ? this part of the error tells me something about 1.8 [custom18.jar:git-Spigot-798f32d-0cd0397]

**Comment by Codisimus** [comment]
There may be a bug with displaying certain loots. If you send me the files of one of the troublesome PhatLoots, I can look into it further.

**Comment by leokiller97** [comment]
Thanks for answering Cody, here's a folder with the PhatLoots that are having this problem: https://www.dropbox.com/s/ti39p6rd9r2ja21/Stuff.zip?dl=0

**Comment by Codisimus** [comment]
I found the issue. Not sure of the cause but you somehow ended up with 'null' items in your loot tables. You can remove them from the save files by finding the item which contains `ItemStack: null` I have fixed the files you sent me and will look into the cause or at least find a way to auto detect and fix these problems in the future.

[Repaired YAML files.zip](https://github.com/Codisimus/PhatLoots/files/389733/Repaired.YAML.files.zip)

**Comment by leokiller97** [comment]
Thanks a lot! I'm not sure how those null items ended up in my files.

**Comment by Codisimus** [comment]
Well you obviously didn't write them in there. There's some broken code somewhere. I will leave this ticket open until I can be sure that this won't happen again.
