### ISSUE TITLE
Phatloots per player

### ISSUE THREAD

**Issue by Rocologo** [Codisimus/PhatLoots#57]
Hi, 

I have a wish for two new features. 

1. Phatloots per player. Cooldown time should be per player, so f.ex a player can on get the loot once a day, another can get the loot if he hasnt opened the chest within the cooldown time.

2. I have some maps (cityworld) on my server, where the chest are pre-genereated (with content). It would be nice if Phatloots could find all these chests and be able to refill then every x time. Or if Phatloots could put some Other) random loots in the chests.

**Comment by Codisimus** [comment]
Hi @Rocologo,

Both of these features already exist. You can read about them on the PhatLoots FAQ page of my website.

1. The feature you are looking for is called global reset. http://codisimus.com/phatloots#faq-global-reset
2. http://codisimus.com/phatloots#faq-minigame-chests

Let me know if you have any other questions.
